---
- name: Deploy and Configure Follower on Openshift on POC Or Cluster A.
  hosts:  openshift
  become: true
  # vars:
  #     oc_service_account_token: "eyJhbGciOiJSUzI1NiIsImtpZCI6ImhJc0dHQ3plX2dqYkpWd1FOUXozYnRpUWVSdjRhSmNEMFZOQWRXV2F6S28ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkYXAiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiZGFwLWZvbGxvd2VyLWRlcGxveS10b2tlbi1weHc4cSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJkYXAtZm9sbG93ZXItZGVwbG95Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYTE1NjNkNzQtNjJkMi00Njc3LWI4ZmQtYTRkZDA1NmY2MTk2Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRhcDpkYXAtZm9sbG93ZXItZGVwbG95In0.3Bjx-eJbiP9ceotpYHp7cs3sNrj3_mti-odsvAHsxuxSrbu4G_rJd4tRqLZ6X_-yyuBl6fFm5z9D-WwnNxZBPqmC38Jm7RLCkGTQaQu5E4UijENU2o8ktFNPm7hQaKgbZPs4ZA17aoOJ93awp3ECAfG2wNHgKnY4wIJHl3CjnGanarxFhgE0rSNieM9q1_xLKFWV_V-svz3R8jP86RsA4oSSahmw9V4iqjfgbohi6cxDaFqGSgvKxrlziEvRDlLAX5AUWFQwzJsdwtTh_2KUz1RbAyy-Cl4-rQq8BZAbUniBwSf-aaSlZiviGDvf991sYfO9GZXFoX8xQqqh8Pl2gw"
  #     api_server_url: "https://kubernetes-api-url:6443"
  vars_files:
    - ../vars/group_vars/poca/all.yml  

  tasks:
    - module_defaults:
        group/k8s:
          validate_certs: no
          kubeconfig: "/root/ocp-install-{{cluster_name}}/auth/kubeconfig"
          
      name: "Run Conjur Follower Tasks on {{cluster_name}}"
      block:
        # - import_role:
        #     name: create-svc-account
        - import_role:
            name: configure-follower
        # - import_role:
        #     name: policies

