---
- name: Deploy PetStore Container and Service
  hosts:  openshift
  become: true
  vars_files:
    - ../vars/group_vars/poca/all.yml  

  tasks:
    - module_defaults:
        group/k8s:
          validate_certs: no
          kubeconfig: "/root/ocp-install-{{cluster_name}}/auth/kubeconfig"
          
      name: Run Conjur Follower Tasks
      block:
        - import_role:
            name: operator-templates
        - import_role:
            name: warehouse
